//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapp.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TemplateDBEntities : DbContext
    {
        public TemplateDBEntities()
            : base("name=TemplateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<TemplatePage> TemplatePages { get; set; }
        public virtual DbSet<TemplateSection> TemplateSections { get; set; }
    }
}
