//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatePage
    {
        public int PageID { get; set; }
        public string PageName { get; set; }
        public string PageTitle { get; set; }
    }
}
